<template><AdminLayout><div class="admin-page"><section class="admin-page-header"><div><div class="admin-page-kicker"><i class="bi bi-envelope"></i> Email</div><h2 class="admin-page-title">Email templates</h2></div><button class="btn-admin" @click="create">New template</button></section>
<section class="admin-grid"><div class="admin-grid__item--4 admin-panel"><div class="admin-panel__body"><button v-for="t in templates" :key="t.id" class="btn btn-light w-100 text-start mb-2" @click="edit(t)">{{t.name}}<small class="d-block">{{t.key}}</small></button></div></div>
<div class="admin-grid__item--8 admin-panel"><div class="admin-panel__body" v-if="selected"><form @submit.prevent="save"><input v-model="form.name" class="form-control mb-2" placeholder="Name" required><input v-model="form.key" class="form-control mb-2" placeholder="key_name" required><input v-model="form.subject" class="form-control mb-2" placeholder="Subject" required><textarea v-model="form.html_body" class="form-control font-monospace mb-2" rows="14" placeholder="HTML editor" required></textarea><input v-model="variablesText" class="form-control mb-2" placeholder="Variables: user_name, order_number"><label><input v-model="form.is_active" type="checkbox"> Active</label><div class="admin-actions mt-3"><button class="btn-admin">Save</button><button v-if="selected.id" type="button" class="btn-admin btn-admin--outline" @click="preview">Preview</button><button v-if="selected.id" type="button" class="btn-admin btn-admin--outline" @click="testSend">Test send</button></div></form><div v-if="previewHtml" class="border rounded p-3 mt-3" v-html="previewHtml"></div></div></div></section></div></AdminLayout></template>
<script setup>
import {computed,onMounted,reactive,ref} from "vue"; import AdminLayout from "@/views/admin/layout/AdminLayout.vue"; import service from "@/services/admin/emailTemplateService";
const templates=ref([]),selected=ref(null),previewHtml=ref(""),form=reactive({key:"",name:"",subject:"",html_body:"",variables:[],is_active:true});
const variablesText=computed({get:()=>form.variables?.join(", ")||"",set:v=>form.variables=v.split(",").map(x=>x.trim()).filter(Boolean)});
const load=async()=>templates.value=(await service.list()).data||[]; const edit=t=>{selected.value=t;Object.assign(form,t);previewHtml.value=""}; const create=()=>edit({id:null,key:"",name:"",subject:"",html_body:"",variables:[],is_active:true});
const save=async()=>{await service.save(selected.value.id,{...form});await load();selected.value=null}; const sampleVars=()=>Object.fromEntries((form.variables||[]).map(v=>[v,`[${v}]`])); const preview=async()=>previewHtml.value=(await service.preview(selected.value.id,sampleVars())).data.html; const testSend=async()=>{const email=prompt("Test recipient email");if(email)await service.test(selected.value.id,email,sampleVars())}; onMounted(load);
</script>
