<?php

return [
    'permission' => 'manage_application_settings',

    'tabs' => [
        'general' => [
            'label' => 'General',
            'description' => 'Platform-wide configuration overview and a scalable container for future environment-driven settings.',
            'icon' => 'bi bi-sliders2',
            'fields' => [],
        ],
        'google_oauth' => [
            'label' => 'Google OAuth',
            'description' => 'Control the Socialite Google login credentials and callback behavior.',
            'icon' => 'bi bi-google',
            'fields' => [
                'GOOGLE_CLIENT_ID' => [
                    'label' => 'Google Client ID',
                    'type' => 'text',
                    'rules' => ['required', 'string', 'max:2048'],
                    'placeholder' => 'Your Google OAuth client ID',
                    'help' => 'Copy this value from Google Cloud Console.',
                    'section' => 'Credentials',
                ],
                'GOOGLE_CLIENT_SECRET' => [
                    'label' => 'Google Client Secret',
                    'type' => 'password',
                    'rules' => ['required', 'string', 'max:2048'],
                    'placeholder' => 'Your Google OAuth client secret',
                    'help' => 'Stored in `.env` and refreshed into runtime config instantly.',
                    'section' => 'Credentials',
                ],
                'GOOGLE_REDIRECT_URI' => [
                    'label' => 'Google Redirect URI',
                    'type' => 'url',
                    'rules' => ['required', 'url', 'max:2048'],
                    'placeholder' => 'https://your-domain.com/api/v1/users/google-callback',
                    'help' => 'Must match the callback registered in the Google OAuth app.',
                    'section' => 'Redirects',
                ],
                'GOOGLE_REDIRECT_URL' => [
                    'label' => 'Google Redirect URL',
                    'type' => 'url',
                    'rules' => ['nullable', 'url', 'max:2048'],
                    'placeholder' => 'Defaults to the redirect URI when left blank',
                    'help' => 'Auto-falls back to GOOGLE_REDIRECT_URI if empty.',
                    'fallback_to' => 'GOOGLE_REDIRECT_URI',
                    'section' => 'Redirects',
                ],
            ],
        ],
        'paymob' => [
            'label' => 'Paymob',
            'description' => 'Configure the only payment gateway and its Unified Checkout channels.',
            'icon' => 'bi bi-credit-card-2-front',
            'fields' => [
                'PAYMOB_ENABLED' => [
                    'label' => 'Paymob Enabled',
                    'type' => 'toggle',
                    'rules' => ['required', 'boolean'],
                    'help' => 'Enable checkout after all Paymob credentials and callback URLs are configured.',
                    'section' => 'Gateway',
                ],
                'PAYMOB_BASE_URL' => [
                    'label' => 'Base URL',
                    'type' => 'url',
                    'rules' => ['required', 'url', 'max:2048'],
                    'placeholder' => 'https://accept.paymob.com',
                    'help' => 'Use the Paymob regional base URL for your merchant account.',
                    'section' => 'Gateway',
                ],
                'PAYMOB_PUBLIC_KEY' => [
                    'label' => 'Public Key',
                    'type' => 'text',
                    'rules' => ['required', 'string', 'max:2048'],
                    'placeholder' => 'pk_live_...',
                    'help' => 'Public key used to launch Unified Checkout.',
                    'section' => 'Credentials',
                ],
                'PAYMOB_SECRET_KEY' => [
                    'label' => 'Secret Key',
                    'type' => 'password',
                    'rules' => ['required', 'string', 'max:2048'],
                    'placeholder' => 'Paymob secret key',
                    'help' => 'Server-side key used to create payment intentions.',
                    'section' => 'Credentials',
                ],
                'PAYMOB_HMAC_SECRET' => [
                    'label' => 'HMAC Secret',
                    'type' => 'password',
                    'rules' => ['required', 'string', 'max:2048'],
                    'placeholder' => 'Paymob HMAC secret',
                    'help' => 'Validates transaction processed and response callbacks.',
                    'section' => 'Credentials',
                ],
                'PAYMOB_CURRENCY' => [
                    'label' => 'Currency',
                    'type' => 'text',
                    'rules' => ['required', 'string', 'size:3'],
                    'placeholder' => 'EGP',
                    'help' => 'Use a 3-letter ISO currency code.',
                    'section' => 'Gateway',
                ],
                'PAYMOB_INTEGRATION_ID_CARD' => [
                    'label' => 'Card Integration ID',
                    'type' => 'number',
                    'rules' => ['required', 'integer', 'min:1'],
                    'help' => 'Integration for Visa, Mastercard, and Meeza when supported.',
                    'section' => 'Payment Methods',
                ],
                'PAYMOB_INTEGRATION_ID_WALLET' => [
                    'label' => 'Wallet Integration ID',
                    'type' => 'number',
                    'rules' => ['required', 'integer', 'min:1'],
                    'help' => 'Integration for Vodafone Cash, Orange Cash, e& cash, WE Pay, and enabled wallets.',
                    'section' => 'Payment Methods',
                ],
                'PAYMOB_INTEGRATION_ID_APPLE_PAY' => [
                    'label' => 'Apple Pay Integration ID',
                    'type' => 'number',
                    'rules' => ['nullable', 'integer', 'min:1'],
                    'help' => 'Leave empty until Apple Pay is enabled for the Paymob account.',
                    'section' => 'Payment Methods',
                ],
                'PAYMOB_IFRAME_ID' => [
                    'label' => 'Legacy Iframe ID',
                    'type' => 'text',
                    'rules' => ['nullable', 'string', 'max:255'],
                    'help' => 'Optional compatibility value; Unified Checkout does not require it.',
                    'section' => 'Checkout',
                ],
                'PAYMOB_CALLBACK_URL' => [
                    'label' => 'Transaction Response URL',
                    'type' => 'url',
                    'rules' => ['required', 'url', 'max:2048'],
                    'placeholder' => 'https://store.example/api/v1/payment/paymob/callback',
                    'help' => 'Customer-facing signed response callback.',
                    'section' => 'Callbacks',
                ],
                'PAYMOB_WEBHOOK_URL' => [
                    'label' => 'Transaction Processed URL',
                    'type' => 'url',
                    'rules' => ['required', 'url', 'max:2048'],
                    'placeholder' => 'https://store.example/api/v1/webhooks/paymob',
                    'help' => 'Server-to-server signed webhook used as the payment source of truth.',
                    'section' => 'Callbacks',
                ],
            ],
        ],
        'mail' => [
            'label' => 'Mail',
            'description' => 'Configure the mail transport and send a real test email from the admin panel.',
            'icon' => 'bi bi-envelope-paper',
            'fields' => [
                'MAIL_MAILER' => [
                    'label' => 'Mail Mailer',
                    'type' => 'select',
                    'rules' => ['required', 'in:smtp,sendmail,log,array,failover,roundrobin,ses,postmark,resend'],
                    'options' => [
                        ['label' => 'SMTP', 'value' => 'smtp'],
                        ['label' => 'Sendmail', 'value' => 'sendmail'],
                        ['label' => 'Log', 'value' => 'log'],
                        ['label' => 'Array', 'value' => 'array'],
                        ['label' => 'Failover', 'value' => 'failover'],
                        ['label' => 'Round Robin', 'value' => 'roundrobin'],
                        ['label' => 'SES', 'value' => 'ses'],
                        ['label' => 'Postmark', 'value' => 'postmark'],
                        ['label' => 'Resend', 'value' => 'resend'],
                    ],
                    'help' => 'Select the Laravel mail transport you want to use by default.',
                    'section' => 'Mailer',
                ],
                'MAIL_SCHEME' => [
                    'label' => 'Mail Scheme',
                    'type' => 'select',
                    'rules' => ['nullable', 'in:tls,ssl,null'],
                    'options' => [
                        ['label' => 'Automatic / None', 'value' => 'null'],
                        ['label' => 'TLS', 'value' => 'tls'],
                        ['label' => 'SSL', 'value' => 'ssl'],
                    ],
                    'help' => 'Leave automatic unless your provider requires a fixed TLS or SSL scheme.',
                    'section' => 'Mailer',
                ],
                'MAIL_HOST' => [
                    'label' => 'Mail Host',
                    'type' => 'text',
                    'rules' => ['required', 'string', 'max:255'],
                    'placeholder' => 'smtp.mailgun.org',
                    'help' => 'SMTP hostname or transport endpoint.',
                    'section' => 'SMTP Credentials',
                ],
                'MAIL_PORT' => [
                    'label' => 'Mail Port',
                    'type' => 'number',
                    'rules' => ['required', 'integer', 'min:1', 'max:65535'],
                    'placeholder' => '587',
                    'help' => 'Network port used by your mail provider.',
                    'section' => 'SMTP Credentials',
                ],
                'MAIL_USERNAME' => [
                    'label' => 'Mail Username',
                    'type' => 'text',
                    'rules' => ['nullable', 'string', 'max:255'],
                    'placeholder' => 'smtp-user',
                    'help' => 'Username or API login for the active mail transport.',
                    'section' => 'SMTP Credentials',
                ],
                'MAIL_PASSWORD' => [
                    'label' => 'Mail Password',
                    'type' => 'password',
                    'rules' => ['nullable', 'string', 'max:2048'],
                    'placeholder' => 'Mail password or API token',
                    'help' => 'Sensitive password or token used by the configured transport.',
                    'section' => 'SMTP Credentials',
                ],
                'MAIL_FROM_ADDRESS' => [
                    'label' => 'From Address',
                    'type' => 'email',
                    'rules' => ['required', 'email', 'max:255'],
                    'placeholder' => 'hello@example.com',
                    'help' => 'Default sender email used by Laravel.',
                    'section' => 'Sender Identity',
                ],
                'MAIL_FROM_NAME' => [
                    'label' => 'From Name',
                    'type' => 'text',
                    'rules' => ['required', 'string', 'max:255'],
                    'placeholder' => 'Your Store',
                    'help' => 'Readable sender name that recipients will see.',
                    'section' => 'Sender Identity',
                ],
            ],
            'actions' => [
                [
                    'key' => 'send_test_email',
                    'label' => 'Send Test Email',
                    'variant' => 'soft',
                ],
            ],
        ],
        'aws_s3' => [
            'label' => 'AWS S3',
            'description' => 'Manage S3 credentials, bucket details, and path-style configuration for file storage.',
            'icon' => 'bi bi-cloud-arrow-up',
            'fields' => [
                'AWS_ACCESS_KEY_ID' => [
                    'label' => 'AWS Access Key ID',
                    'type' => 'text',
                    'rules' => ['nullable', 'string', 'max:255'],
                    'placeholder' => 'AKIA...',
                    'help' => 'Access key used to authenticate to AWS S3.',
                    'section' => 'Credentials',
                ],
                'AWS_SECRET_ACCESS_KEY' => [
                    'label' => 'AWS Secret Access Key',
                    'type' => 'password',
                    'rules' => ['nullable', 'string', 'max:2048'],
                    'placeholder' => 'AWS secret key',
                    'help' => 'Sensitive secret associated with the configured access key.',
                    'section' => 'Credentials',
                ],
                'AWS_DEFAULT_REGION' => [
                    'label' => 'AWS Default Region',
                    'type' => 'text',
                    'rules' => ['required', 'string', 'max:255'],
                    'placeholder' => 'us-east-1',
                    'help' => 'Region where the S3 bucket lives.',
                    'section' => 'Bucket',
                ],
                'AWS_BUCKET' => [
                    'label' => 'AWS Bucket',
                    'type' => 'text',
                    'rules' => ['nullable', 'string', 'max:255'],
                    'placeholder' => 'your-bucket-name',
                    'help' => 'Target bucket name used by the storage driver.',
                    'section' => 'Bucket',
                ],
                'AWS_USE_PATH_STYLE_ENDPOINT' => [
                    'label' => 'Use Path Style Endpoint',
                    'type' => 'toggle',
                    'rules' => ['required', 'boolean'],
                    'help' => 'Enable this when using compatible S3 providers that require path-style URLs.',
                    'section' => 'Bucket',
                ],
            ],
        ],
    ],
];
